name: Deploy Based on Tag
 
on:
  push:
    tags:
      - 'dev-*'
      - 'QA-*'
 
jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ startsWith(github.ref, 'refs/tags/dev-') && 'self-hosted' || startsWith(github.ref, 'refs/tags/QA-') && 'self-hosted' }}
 
    steps:
      - name: Determine Runner
        id: determine-runner
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/dev-* ]]; then
            echo "::set-output name=runner::dev"
          elif [[ "${GITHUB_REF}" == refs/tags/QA-* ]]; then
            echo "::set-output name=runner::QA"
          fi
 
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
 
      - name: Install dependencies
        run: npm install
 
      - name: Build the project
        run: npm run build
 
      - name: Deploy to Environment
        run: |
          echo "Deploying to ${{ steps.determine-runner.outputs.runner }} Environment"
          # Your deployment script or commands for the environment
