name: ACHIEVE-Service-CICD

on:
  push:
    branches:
      - '**'
    tags:  
      - 'dev_v*'  
      - 'uat_v*'    
      - 'qa_v*'  
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
          - DEV
          - QA
          - UAT

jobs:
  deploymentjob:
    name: Deployment Job
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    outputs:
      ENV: ${{ steps.determine_environment.outputs.env }}
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Determine Environment
        id: determine_environment
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: |
         echo "Event Name: $GITHUB_EVENT_NAME"
          echo "Ref: $GITHUB_REF"
          if ($GITHUB_EVENT_NAME -eq "workflow_dispatch") {
            echo "::set-output name=env::DEV"
          } elseif ($GITHUB_REF -match '^refs/tags/dev_v.*') {
            echo "::set-output name=env::DEV"
          } elseif ($GITHUB_REF -match '^refs/tags/uat_v.*') {
            echo "::set-output name=env::UAT"
          } elseif ($GITHUB_REF -match '^refs/tags/qa_v.*') {
            echo "::set-output name=env::QA"
          }

         

  dev_deployment:
    name: DEV Deployment
    needs: deploymentjob
    if: ${{ needs.deploymentjob.outputs.ENV == 'DEV' }}
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV environment"

  qa_deployment:
    name: QA Deployment
    needs: deploymentjob
    if: ${{ needs.deploymentjob.outputs.ENV == 'QA' }}
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to QA
        run: |
          echo "Deploying to QA environment"
